### ISSUE TITLE
prepare_NWPU.m cannt run 

### ISSUE THREAD

**Issue by sailyung** [gjy3035/NWPU-Crowd-Sample-Code#1]
Error in preapre_NWPU (line 87)
        im_dots = get_dot_map(im,annPoints);

**Comment by sailyung** [comment]
it is an undefined function, and also with get_density_map_gaussian function

**Comment by gjy3035** [comment]
Sorry, it's my negligence. The generation codes for density maps and dot maps have been uploaded.

**Comment by sailyung** [comment]
thank for your good job
