### ISSUE TITLE
Where can I found calc_psnr and calc_ssim?

### ISSUE THREAD

**Issue by MagazzuGaetano** [gjy3035/NWPU-Crowd-Sample-Code#10]
I was trying to reproduce the validation results, I was able to get the same results for MSE and MAE, but I got different results for PSNR and SSIM. (I'm using the pretrained models provided)

Now I'm using skimage.metrics:
```python
from skimage.metrics import structural_similarity as ssim
from skimage.metrics import peak_signal_noise_ratio as psnr
```
I can't find the "qualitycc" import anywhere.
Where can I find the two functions "calc_psnr" and "calc_ssim" placed inside validation.py?

**Comment by gjy3035** [comment]
https://github.com/gaoguangshuai/survey-for-crowd-counting/tree/master/Python-script

**Comment by MagazzuGaetano** [comment]
thanks!
