### ISSUE TITLE
Why perform crop in validation and test?

### ISSUE THREAD

**Issue by BJTUJia** [gjy3035/NWPU-Crowd-Sample-Code#12]
Dear author, thanks very much for this excellent repo.  But I am confusing the crop operations in validate and test, as shown in the attached figure.  What's the purpose of this operation? Is it a form of data augmentation or a trick to improve the test performance? I can't find any explanation in the paper. 

Also, can you give me some advice on the data augmentation? Should we use random crop? i.e.  to resize the input image to a larger size and randomly crop a specific sized? 
I read in the ACSCP paper that says such operation is not appropriate since the image interpolation may change the crowd count from a density map.  What's your view on this matter?

Looking forward to your answer!@gjy3035
![image](https://user-images.githubusercontent.com/24791613/85124860-2e7f0380-b25d-11ea-9020-fd107cd4da38.png)

**Comment by gjy3035** [comment]
Our repo processes high-resolution images (~2048pixels). Some networks need more than 12GB memory. So we need to crop the test images with a small size. 
Our interpolation operation is pre-processed before the training phase and saves the dot map, and the cropping is on the dot map. Thus, the counting number is just suffered from a very slight fluctuation.

**Comment by BJTUJia** [comment]
Thanks very much. I see that now.
