### ISSUE TITLE
how to change the network when training

### ISSUE THREAD

**Issue by xiaomeng654321** [gjy3035/NWPU-Crowd-Sample-Code#15]
the config of MCNN is default loaded when training, I can't find the code to change the default loaded config
Could you help me about this?

**Comment by gjy3035** [comment]
https://github.com/gjy3035/NWPU-Crowd-Sample-Code/blob/21fbeb8dd36070d0f8f2ce7906ad983043e1cfba/config.py#L15

supported networks:
https://github.com/gjy3035/NWPU-Crowd-Sample-Code/tree/master/models/counters

**Comment by xiaomeng654321** [comment]
@gjy3035 I get it, thanks a lot for you  and all of the code
