### ISSUE TITLE
quailitycc is missed, required in validation.py

### ISSUE THREAD

**Issue by OShapovalov** [gjy3035/NWPU-Crowd-Sample-Code#17]
from quailitycc import calc_psnr, calc_ssim

https://github.com/gjy3035/NWPU-Crowd-Sample-Code/blob/21fbeb8dd36070d0f8f2ce7906ad983043e1cfba/validation.py#L17

**Comment by Elin24** [comment]
I have uploaded [qualitycc.py](https://github.com/gjy3035/NWPU-Crowd-Sample-Code/blob/master/qualitycc.py) to the repo, and the following change you should check: [update validation.py file](https://github.com/gjy3035/NWPU-Crowd-Sample-Code/commit/bac9a2ee52123daff07cc1d6086b59b973a0721a).

**Comment by OShapovalov** [comment]
Thank you for fast reply and fix! Now it works)
