### ISSUE TITLE
Training takes too long

### ISSUE THREAD

**Issue by klauspa** [gjy3035/NWPU-Crowd-Sample-Code#18]
Hello, I used four rtx2080Ti GPU cards to train the SCAR model on NWPU dataset, after 30 more hours or 600 epochs, the mae is around 170 which is poor performance(110 on  Crowd benchmark). Is it normal because the max_epoch is set to be 2000 or something went wrong?

**Comment by gjy3035** [comment]
Please check your [setting](https://github.com/gjy3035/NWPU-Crowd-Sample-Code/tree/master/saved_exp_para/SCAR). SCAR's training should be finished in ~300 epoch.
