### ISSUE TITLE
Any plan to release the pretrained model on this new benchmark?

### ISSUE THREAD

**Issue by dongzelian** [gjy3035/NWPU-Crowd-Sample-Code#2]

**Comment by gjy3035** [comment]
We will release the pre-trained models after the Chinese New Year. Thanks for your attention!

**Comment by gjy3035** [comment]
@dongzelian The pre-trained models are released in this [link](http://share.crowdbenchmark.com:2443/home/Pre-trained_Models_NWPU-Crowd).

**Comment by alana314** [comment]
The link no longer works, do you have another? Thank you
