### ISSUE TITLE
Do you have python code for processing mat file?

### ISSUE THREAD

**Issue by FanShuixing** [gjy3035/NWPU-Crowd-Sample-Code#3]
Thanks for your work! I have noticed there is need to run mat file with matlab in data preparation? Is there a python code for this purpose?

**Comment by gjy3035** [comment]
Line 32 in https://github.com/gjy3035/NWPU-Crowd-Sample-Code/blob/master/datasets/basedataset.py can process the orginal labels to generate dot map.

**Comment by FanShuixing** [comment]
Thanks for your reply. I want to do crowd counting using my own dataset , but i just have the box information for every instance(the detection label information).I have noticed the original crowding count dataset has the mat file as it's label information, and then using matlab to transform this mat file to csv file as model needs.Do i need to make mat file as label if I want to do crowd counting ? I am Unfamiliar with matlab, so it is diffcult for me to do this .Do you have other suggestions ?

**Comment by gjy3035** [comment]
detection: box label
counting: point label

If you want to use this code, you need to use the center of the box as the point, then you need generate the dot map (binary image) using the obtained points. As a result, you do not need the mat or csv file.

**Comment by FanShuixing** [comment]
Thanks for your suggestion.
