### ISSUE TITLE
能否提供一下预训练模型，数据集太大需要训练很久

### ISSUE THREAD

**Issue by BrownSweater** [gjy3035/NWPU-Crowd-Sample-Code#5]

**Comment by gjy3035** [comment]
抱歉，由于肺炎疫情无法返校，服务器无法使用。后期将会提供预训练模型。感谢关注！

**Comment by BrownSweater** [comment]
> 抱歉，由于肺炎疫情无法返校，服务器无法使用。后期将会提供预训练模型。感谢关注！

我找到了resnet系列在某些数据集上性能较差的原因。是由BN引起的。在batch size = 1 时，在某些数据集上（SHHA）BN会大大降低性能。但是vgg系列由于网络很浅无需使用BN。在trainer.py中加入以下代码即可解决。再次感谢您优秀的工作。
```
    def fix_bn(slef, m):
        classname = m.__class__.__name__
        if classname.find('BatchNorm') != -1:
            m.eval()

    def train(self): # training for all datasets
        self.net.train()
        if self.train_batchsize > 1:
            pass
        else:
            self.net.apply(self.fix_bn)
            print(f'train batch size: {self.train_batchsize}, BN is eval mode')
        for i, data in enumerate(self.train_loader, 0):
            self.timer['iter time'].tic()
            img, gt_map = data
            img = Variable(img).cuda()
            gt_map = Variable(gt_map).cuda()
       ...
```

**Comment by gjy3035** [comment]
@BrownSweater 感谢指出这个问题。之前我尝试过替换成IN（像SANet提出的那样），但是在Shanghai A效果并不明显。可否分享一下你在替换之后的实验结果呢？

**Comment by BrownSweater** [comment]
> @BrownSweater 感谢指出这个问题。之前我尝试过替换成IN（像SANet提出的那样），但是在Shanghai A效果并不明显。可否分享一下你在替换之后的实验结果呢？

MAE是72.1。到那时由于设备原因我是使用了Adam来加快收敛速度。如果使用SGD的话效果应该能在好一点。

**Comment by gjy3035** [comment]
@BrownSweater 你好，预训练模型我们已经上传至此链接：http://share.crowdbenchmark.com:2443/home/Pre-trained_Models_NWPU-Crowd

目前，SFCN+还未上传，其预训练模型在另一台未开机的服务器上。在返校后我会尽快上传。

感谢关注！

**Comment by gjy3035** [comment]
@BrownSweater SFCN+的预训练模型已经上传至同一地址下。
