### ISSUE TITLE
关于训练过程中碰到的dot文件缺失的问题

### ISSUE THREAD

**Issue by homurajiang** [gjy3035/NWPU-Crowd-Sample-Code#6]
您好，我将NWPU训练集按照folder-tree放置后，在尝试运行train.py文件时，遇到了如下错误
`FileNotFoundError: [Errno 2] No such file or directory: '../ProcessedData/NWPU-Crowd\\dot\\1073.png'`

提示缺少dot，然后您在baseddataset.py文件中确实有读取dot和mat的操作
`        self.imgfileTemp = os.path.join(data_path, 'ima', '{}.jpg')
        self.matfileTemp = os.path.join(data_path, 'mat', '{}.mat')
        self.dotfileTemp = os.path.join(data_path, 'dot', '{}.png')`
可否提供一下dot的生成方式或是提供dot文件呢，感谢 ：)

**Comment by gjy3035** [comment]
You need to pre-process the original data by running the Matlab code: ```./datasets/prepare_NWPU.m```.

**Comment by homurajiang** [comment]
thx！
