### ISSUE TITLE
如何复现精度

### ISSUE THREAD

**Issue by BrownSweater** [gjy3035/NWPU-Crowd-Sample-Code#8]
仓库中的参数和saved_exp_para中的参数不一致。
1、优化器是选择adam吗？
2、是否使用了weight decay？
3、学习率是多少，是否有学习率衰减？

**Comment by gjy3035** [comment]
优化器相关参数在这里：https://github.com/gjy3035/NWPU-Crowd-Sample-Code/blob/231620293687c82a4c1449195c3a4e7799fcd241/trainer.py#L28
采用saved_exp_para中的参数，即可完全复现结果。
学习率和衰减设置也在saved_exp_para中。
