### ISSUE TITLE
Download link is not accessible

### ISSUE THREAD

**Issue by ijanerik** [gjy3035/NWPU-Crowd-Sample-Code#9]
The link provided in the readme is not accessible. It looks like my access is not enough to view the page. Could the download page still be on private?

Kind regards,
Jan Erik van Woerden

**Comment by gjy3035** [comment]
you can download from this link:
https://mailnwpueducn-my.sharepoint.com/personal/gjy3035_mail_nwpu_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fgjy3035%5Fmail%5Fnwpu%5Fedu%5Fcn%2FDocuments%2F%E8%AE%BA%E6%96%87%E5%BC%80%E6%BA%90%E6%95%B0%E6%8D%AE%2FNWPU%2DCrowd&originalPath=aHR0cHM6Ly9tYWlsbndwdWVkdWNuLW15LnNoYXJlcG9pbnQuY29tLzpmOi9nL3BlcnNvbmFsL2dqeTMwMzVfbWFpbF9ud3B1X2VkdV9jbi9Fc3ViTXA0OHd3SkRpSDBZbFQ4Mk5ZWUJtWTlMMHMtRnByckJjb2FBSmtJMXJ3P3J0aW1lPXFJZm9pRXZWMTBn
or
http://share.crowdbenchmark.com:2443/home/NWPU-Crowd_Dataset
